route:
  receiver: 'remediation-hook'
  group_by: ['alertname']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1m

receivers:
- name: 'remediation-hook'
  webhook_configs:
  - url: 'http://host.docker.internal:5001/webhook'